services:
  palui:
    build: .
    container_name: palui
    restart: unless-stopped
    environment:
      PGID: 10
      PUID: 1000
      PALWORLD_API_BASE_URL: "http://192.168.10.3:8212"
      PALWORLD_STATS_COMMAND: "info"
      PALWORLD_API_USERNAME: "admin"
      PALWORLD_API_PASSWORD: "baron123"
      PALWORLD_API_TOKEN: ""
      PALWORLD_API_TOKEN_HEADER: "Authorization"
      PALWORLD_API_TOKEN_PREFIX: "Bearer"
      PALWORLD_CONFIG_DIR: "/palworld/Pal/Saved/Config/LinuxServer"
    volumes:
      - /volume1/Games/palworld:/palworld:rw
    networks:
      physical_eth:
        ipv4_address: 192.168.10.7

networks:
  physical_eth:
    external: true
    name: palworld-server_physical_eth
